<?php

require_once 'TicketRepository.php';
require_once 'database.php';
require('fpdf/fpdf.php');
require('auth.php');
require_login();

$userId = $_SESSION['user_id'] ?? null;
$ticketId = isset($_GET['id']) ? (int)$_GET['id'] : 0;

if (!$userId || $ticketId <= 0) {
    die('Invalid request.');
}

$ticketRepository = new TicketRepository($pdo);
$ticket = $ticketRepository->getByIdAndUser($ticketId, (int)$userId);

if (!$ticket) {
    die("Ticket not found");
}

$title = $ticket->getTitle();
$description = $ticket->getDescription();
$status = $ticket->getStatus();
$priority = $ticket->getPriority();
$createdBy = $ticket->getCreatedBy();
$assignedTo = $ticket->getAssignedTo();
$createdAt = $ticket->getCreatedAt();
$updatedAt = $ticket->getUpdatedAt();

$pdf = new FPDF();
$pdf->AddPage();

$pdf->SetTitle('Tickify Ticket PDF');
$pdf->SetAutoPageBreak(true, 20);

$pdf->SetFont("Arial", "B", 24);
$pdf->Cell(0, 15, "Tickify - Ticket Summary", 0, 1, "C");

$pdf->SetFont("Arial", "I", 14);
$pdf->SetTextColor(52, 73, 94);
$pdf->Cell(0, 10, "Official Ticket Report", 0, 1, "C");

$pdf->SetTextColor(0, 0, 0);
$pdf->Ln(8);

$pdf->SetFont("Arial", "B", 12);
$pdf->Cell(50, 8, "Ticket ID:", 0, 0);
$pdf->SetFont("Arial", "", 12);
$pdf->Cell(0, 8, (string)$ticketId, 0, 1);

$pdf->SetFont("Arial", "B", 12);
$pdf->Cell(50, 8, "Title:", 0, 0);
$pdf->SetFont("Arial", "", 12);
$pdf->Cell(0, 8, $title, 0, 1);

$pdf->SetFont("Arial", "B", 12);
$pdf->Cell(50, 8, "Status:", 0, 0);
$pdf->SetFont("Arial", "", 12);
$pdf->Cell(0, 8, $status, 0, 1);

$pdf->SetFont("Arial", "B", 12);
$pdf->Cell(50, 8, "Priority:", 0, 0);
$pdf->SetFont("Arial", "", 12);
$pdf->Cell(0, 8, (string)$priority, 0, 1);

$pdf->SetFont("Arial", "B", 12);
$pdf->Cell(50, 8, "Created By:", 0, 0);
$pdf->SetFont("Arial", "", 12);
$pdf->Cell(0, 8, (string)$createdBy, 0, 1);

$pdf->SetFont("Arial", "B", 12);
$pdf->Cell(50, 8, "Assigned To:", 0, 0);
$pdf->SetFont("Arial", "", 12);
$pdf->Cell(0, 8, (string)$assignedTo, 0, 1);

$pdf->SetFont("Arial", "B", 12);
$pdf->Cell(50, 8, "Created At:", 0, 0);
$pdf->SetFont("Arial", "", 12);
$pdf->Cell(0, 8, (string)$createdAt, 0, 1);

$pdf->SetFont("Arial", "B", 12);
$pdf->Cell(50, 8, "Updated At:", 0, 0);
$pdf->SetFont("Arial", "", 12);
$pdf->Cell(0, 8, (string)$updatedAt, 0, 1);

$pdf->Ln(8);

$pdf->SetFont("Arial", "B", 12);
$pdf->Cell(0, 10, "Description", 1, 1, "L");

$pdf->SetFont("Arial", "", 12);
$pdf->MultiCell(0, 8, $description, 1, "L");

$pdf->Ln(10);

$pdf->SetFont("Arial", "B", 11);
$pdf->SetTextColor(120, 120, 120);
$pdf->Cell(0, 8, "Generated by Tickify", 0, 1, "C");

$pdf->Output("I", "ticket_" . $ticketId . ".pdf");
?>